openapi: 3.0.1
info:
  title: ReportParseAPI
  description: API Definition of ReportParseAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/reports
paths:
  /invoiceDetails:
    get:
      responses:
        default:
          description: Default response
  /productsSummary:
    get:
      responses:
        default:
          description: Default response
  /summaryPerCategories:
    get:
      responses:
        default:
          description: Default response
  /evolutionByProduct:
    get:
      responses:
        default:
          description: Default response
  /evolutionByCategory:
    get:
      responses:
        default:
          description: Default response
